- name: Install Apache
 gather_facts: false
 hosts: all
 # become: true
 # Do not assume root, to execute playbooks over command bus
 connection: local
 tasks:
  - name: Update apt package cache
   ansible.builtin.apt:
    update_cache: yes
 
  - name: Install or Upgrade Apache
   ansible.builtin.apt:
    name: apache2
    state: latest
 
  - name: Start Apache service
   service:
    name: apache2
    state: started